package U2_Proyecto;
/**
 * @author Isaias
 */
public class Principal {
    public static void main(String[] args) {
                Punto figura[] = {new Punto(15,50),
                          new Punto(25,50),
                          new Punto(45,50),
                          new Punto(100,50),
                          new Punto(125,50),
                          new Punto(125,100),
                          new Punto(200,100),
                          new Punto(200,125),
                          new Punto(200,150),
                          new Punto(150,150),
                          new Punto(125,150),
                          new Punto(125,175),
                          new Punto(125,200),
                          new Punto(100,200),
                          new Punto(75,200),
                          new Punto(50,200),
                          new Punto(25,200),
                          new Punto(15,200),
                          new Punto(15,175),
                          new Punto(15,150),
                          new Punto(25,150),
                          new Punto(50,150),
                          new Punto(65,150),
                          new Punto(65,140),
                          new Punto(65,130),
                          new Punto(50,130),
                          new Punto(25,130),
                          new Punto(15,130),
                          new Punto(15,125),
                          new Punto(15,115),
                          new Punto(45,115),
                          new Punto(65,115),
                          new Punto(65,95),
                          new Punto(55,95),
                          new Punto(25,95),
                          new Punto(15,95),
                          new Punto(15,85),
                          new Punto(15,75),
                          new Punto(15,65),
                          new Punto(15,55),
                          new Punto(15,50),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
                          //new Punto(,),
        };
        //Crear instancia de ventana
        new Ventana("Proyecto Unidad 2", figura);
    }
}
